---
- name: install grafana
  hosts: all
  tasks:

    - name: install packages
      package:
       name: "{{ item }}"
       state: present
      loop:
        - musl
        - libfontconfig1
        - adduser





    - name: get url
      ansible.builtin.get_url:
        url: https://dl.grafana.com/oss/release/grafana_11.0.0_amd64.deb
        dest: /home/host2/
    - name: install grafana
      ansible.builtin.shell: dpkg -i /home/host2/grafana_11.0.0_amd64.deb


    - name: daemon reload
      become: yes
      systemd:
        daemon-reload: true

    - name: start grafana
      become: yes
      systemd:
        name: grafana-server
        state: started

    - name: enable grafana
      become: yes
      systemd:
        name: grafana-server
        enabled: yes


